name: GuildsAddons
version: ${project.version}
main: koral.guildsaddons.GuildsAddons
api-version: 1.16
commands:
  turbodrop:
    description: Podwaja Drop z Cobla
    permission: guildsaddons.turbodrop
    usage: /turbodrop <nick | @server> <czas w minutach>
  drop:
    description: umozliwoa edycje dropu ze stone
    permission: guildsaddons.drop
  schowek:
    description: otwiera schowek
    permission: guildsaddons.schowek
  setrtp:
    description: ustawia rtp
    permission: guildsaddons.setrtp
  delhome:
    permission: guildsaddons.delhome
    usage: /sethome <nazwa>
  sethome:
    permission: guildsaddons.sethome
    usage: /sethome <nazwa>
  home:
    permission: guildsaddons.home
    usage: /home (nazwa)
  itemshop:
    permission: guildsaddons.itemshop
    usage: /is
  isadmin:

permissions:
  home.others:
    default: false
