name: GuildsAddons
version: ${project.version}
main: koral.guildsaddons.GuildsAddons
depend: [WorldGuard, WorldEdit]
api-version: 1.16
commands:
  turbodrop:
    description: Podwaja Drop z Cobla
    permission: guildsaddons.turbodrop
    usage: /turbodrop <nick | @server> <czas w minutach>
  drop:
    description: umozliwoa edycje dropu ze stone
    permission: guildsaddons.drop
  schowek:
    description: otwiera schowek
    permission: guildsaddons.schowek
  setrtp:
    description: ustawia rtp
    permission: guildsaddons.setrtp
  delhome:
    permission: guildsaddons.delhome
    usage: /sethome <nazwa>
  rtp:
    permission: guildsaddons.rtp
    usage: /rtp <player>
  sethome:
    aliases: [ustawdom, ustawhome]
    permission: guildsaddons.sethome
    usage: /sethome <nazwa>
  home:
    aliases: [dom]
    permission: guildsaddons.home
    usage: /home (nazwa)
  itemshop:
    aliases: [is]
    permission: guildsaddons.itemshop
    usage: /is
  isadmin:
    permission: guildsaddons.isadmin
  isedit:
    permission: guildsaddons.isadmin
  gildia:
    aliases: [guild, g]
    permission: guildsaddons.gildia
  gadmin:
    permission: guildsaddons.gadmin
  pvp:
    permission: guildaddons.pvp
    usage: /pvp <nick>

permissions:
  home.others:
    default: false
